services:
  # Backend API
  - type: web
    name: mern-auth-api
    runtime: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend
  - type: web
    name: mern-auth-client
    runtime: static
    region: oregon
    plan: free
    rootDir: client1
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        sync: false
